# Generated by Django 5.0.6 on 2024-06-19 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('last_name2', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Número de Celular')),
                ('address', models.CharField(max_length=100, verbose_name='domicilio')),
                ('city', models.CharField(max_length=50, verbose_name='localidad')),
                ('state', models.CharField(max_length=50, verbose_name='provincia')),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.paciente', verbose_name='Paciente')),
            ],
        ),
    ]
