# Generated by Django 5.0.6 on 2024-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cita_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('date', 'time', 'patient'), name='unique_appointment'),
        ),
    ]
