# Generated by Django 5.0.6 on 2024-06-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cita_unique_appointment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='unique_appointment',
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='unique_appointment'),
        ),
    ]
